server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#mybatis-plus的逻辑删除和主键配置等
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键生成策略
      id-type: auto            
  mapper-locations: classpath:mapper/*.xml

#配合后台调取中台服务使用,只有在启动聚合服务的时候才会有该配置,两个模块内部进行调用
aggregation:
  remote-url: http://127.0.0.1:${server.port}

#自定义的一些配置
link:
  #用户短链分组最大数量限制
  group:
    max-num: 15
  #限流
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  #高德地图key
  locale:
    stats:
      amap-key: b8ab4b0ee1f1af9fc7a2c7f1df2ef586
  domain:
    default: shortlink.com:8003
  goto-domain:
    white-list:
      enable: false
      names: "哔哩哔哩,quan_blog"
      details:
        - bilibili.com
        - aquan.online
