server:
  port: 8001


spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto            # 主键生成策略，可以根据你的需求配置
  mapper-locations: classpath:mapper/*.xml

#高德地图key
link:
  locale:
    stats:
      amap-key: b8ab4b0ee1f1af9fc7a2c7f1df2ef586
  domain:
    default: shortlink.com:8001
  goto-domain:
    white-list:
      enable: true
      names: "哔哩哔哩,quan_blog"
      details:
        - bilibili.com
        - aquan.online

